# in .github/workflows/continuous_integration.yml
name: Continuous integration
on: [push, pull_request]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - run:

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm run format

  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm run lint
